# Generated by Django 3.1.7 on 2021-02-28 07:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_auto_20210228_0741'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bid',
            name='last_bidder',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bidder', to='auctions.user'),
        ),
    ]
