# Generated by Django 3.1.7 on 2021-02-28 08:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_auto_20210228_0743'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='last_bid',
        ),
        migrations.AddField(
            model_name='bid',
            name='bid_item',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='bid_item', to='auctions.listing'),
            preserve_default=False,
        ),
    ]
