# Generated by Django 3.1.7 on 2021-02-28 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0010_auto_20210228_1243'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='watchlist_item_count',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='watchlist_item_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
