# Generated by Django 3.1.7 on 2021-02-28 14:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0012_auto_20210228_1442'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='watchlist_item_id',
        ),
        migrations.AddField(
            model_name='listing',
            name='watchers',
            field=models.ManyToManyField(related_name='watchers', to=settings.AUTH_USER_MODEL),
        ),
    ]
