# Generated by Django 3.1.7 on 2021-03-02 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0020_auto_20210302_1211'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='item_count',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
